{"name": "test_get_ner", "status": "broken", "statusDetails": {"message": "AttributeError: 'tuple' object has no attribute 'iterrows'", "trace": "self = <test_get_ner.TestNer object at 0x00000242B0AB0518>\n\n    @pytest.mark.apitest\n    @allure.feature(\"Ner实体识别\")\n    def test_get_ner(self):\n>       GetNer.get_ner(self, \"bio_char.txt\", \"bio_char_result.csv\", \"ner_test_result.csv\", \"tag.txt\")\n\napi\\test_get_ner.py:19: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\api\\get_ner.py:72: in get_ner\n    \"{:.2f}%\".format(tf_list.count(\"FALSE\") / len(tf_list) * 100))\n..\\api\\get_ner.py:42: in get_ner_result\n    ???\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <test_get_ner.TestNer object at 0x00000242B0AB0518>\ntest_data_file = 'ner_test_result.csv'\n\n>   ???\nE   AttributeError: 'tuple' object has no attribute 'iterrows'\n\n..\\api\\get_ner.py:26: AttributeError"}, "start": 1585727784786, "stop": 1585727978123, "uuid": "52682c70-6ee1-4293-afc2-17ec85aa8b3a", "historyId": "d8540c5ad7e84c36960538bd2f6c1a29", "testCaseId": "c9ca9e117f821440dd422ad8374b0348", "fullName": "pytest.api.test_get_ner.TestNer#test_get_ner", "labels": [{"name": "feature", "value": "Ner实体识别"}, {"name": "tag", "value": "apitest"}, {"name": "parentSuite", "value": "pytest.api"}, {"name": "suite", "value": "test_get_ner"}, {"name": "subSuite", "value": "TestNer"}, {"name": "host", "value": "WIN-OQ20V7UABJF"}, {"name": "thread", "value": "22000-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "pytest.api.test_get_ner"}]}